trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: JavaToolInstaller@1
  displayName: 'Configurar Java 21'
  inputs:
    versionSpec: '21'
    jdkArchitecture: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: Maven@4
  displayName: 'Build e Pacote (Maven)'
  inputs:
    mavenPomFile: 'ignis_orbital/pom.xml'
    mavenOptions: '-Xmx3072m'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.21' 
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    goals: 'clean package -DskipTests'

- script: |
    echo "Arquivos gerados:"
    find . -name "*.jar"
  displayName: 'Listar JARs gerados'

- script: |
    echo "PIPELINE YAML EXECUTADA"
    echo "SKIP TESTS ATIVO"
  displayName: 'Diagnóstico'

- task: CopyFiles@2
  displayName: 'Copiar o pacote gerado (.jar)'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/target/*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publicar o Artefato (Drop)'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
