-- Ignis Orbital - DDL

BEGIN
    FOR t IN (
        SELECT table_name
        FROM user_tables
        WHERE table_name IN (
            'GS_HISTORICO_LOG', 'GS_TELEMETRIA_RAW', 'GS_ALERTAS',
            'GS_USUARIOS', 'GS_REGIOES', 'GS_SATELITES'
        )
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

BEGIN
    FOR s IN (
        SELECT sequence_name
        FROM user_sequences
        WHERE sequence_name IN (
            'SEQ_USUARIO', 'SEQ_REGIAO', 'SEQ_SATELITE',
            'SEQ_ALERTA', 'SEQ_LOG', 'SEQ_TELEMETRIA'
        )
    ) LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
    END LOOP;
END;
/

CREATE TABLE GS_USUARIOS (
    ID_USUARIO    NUMBER(10)       NOT NULL,
    NOME          VARCHAR2(100)    NOT NULL,
    EMAIL         VARCHAR2(100)    NOT NULL,
    SENHA_HASH    VARCHAR2(255)    NOT NULL,
    PERFIL        VARCHAR2(20)     NOT NULL,
    DT_CADASTRO   TIMESTAMP        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_GS_USUARIOS PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UK_GS_USUARIOS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_GS_USUARIOS_PERFIL CHECK (
        PERFIL IN ('ADMIN', 'ANALISTA', 'OPERADOR', 'VISUALIZADOR')
    )
);

CREATE TABLE GS_REGIOES (
    ID_REGIAO           NUMBER(10)    NOT NULL,
    NM_REGIAO           VARCHAR2(100) NOT NULL,
    DS_BIOMA            VARCHAR2(50)  NOT NULL,
    NR_CRITICIDADE_BASE NUMBER(3)     NOT NULL,
    SG_UF               CHAR(2)       NOT NULL,
    CONSTRAINT PK_GS_REGIOES PRIMARY KEY (ID_REGIAO),
    CONSTRAINT CK_GS_REGIOES_BIOMA CHECK (
        DS_BIOMA IN ('AMAZONIA', 'CERRADO', 'PANTANAL', 'MATA_ATLANTICA', 'CAATINGA', 'PAMPA')
    ),
    CONSTRAINT CK_GS_REGIOES_CRITICIDADE CHECK (
        NR_CRITICIDADE_BASE BETWEEN 1 AND 10
    )
);

CREATE TABLE GS_SATELITES (
    ID_SATELITE   NUMBER(10)    NOT NULL,
    NM_SATELITE   VARCHAR2(100) NOT NULL,
    DS_SENSOR     VARCHAR2(100) NOT NULL,
    DS_ORBITA     VARCHAR2(50),
    DT_LANCAMENTO DATE,
    CONSTRAINT PK_GS_SATELITES PRIMARY KEY (ID_SATELITE),
    CONSTRAINT UK_GS_SATELITES_NOME UNIQUE (NM_SATELITE)
);

CREATE TABLE GS_ALERTAS (
    ID_ALERTA      NUMBER(10)     NOT NULL,
    ID_REGIAO      NUMBER(10)     NOT NULL,
    ID_SATELITE    NUMBER(10)     NOT NULL,
    NR_LATITUDE    NUMBER(10,6)   NOT NULL,
    NR_LONGITUDE   NUMBER(10,6)   NOT NULL,
    VL_TEMPERATURA NUMBER(5,2)    NOT NULL,
    DS_RISCO       VARCHAR2(20)   NOT NULL,
    DS_STATUS      VARCHAR2(20)   NOT NULL,
    DT_CAPTURA     TIMESTAMP      NOT NULL,
    CONSTRAINT PK_GS_ALERTAS PRIMARY KEY (ID_ALERTA),
    CONSTRAINT FK_GS_ALERTAS_REGIAO FOREIGN KEY (ID_REGIAO)
        REFERENCES GS_REGIOES (ID_REGIAO),
    CONSTRAINT FK_GS_ALERTAS_SATELITE FOREIGN KEY (ID_SATELITE)
        REFERENCES GS_SATELITES (ID_SATELITE),
    CONSTRAINT CK_GS_ALERTAS_RISCO CHECK (
        DS_RISCO IN ('ALTO', 'MEDIO', 'BAIXO')
    ),
    CONSTRAINT CK_GS_ALERTAS_STATUS CHECK (
        DS_STATUS IN ('DETECTADO', 'EM_ANALISE', 'CONTIDO', 'ESCALADO')
    )
);

CREATE TABLE GS_HISTORICO_LOG (
    ID_LOG      NUMBER(10)    NOT NULL,
    ID_ALERTA   NUMBER(10),
    ID_USUARIO  NUMBER(10),
    DS_ACAO     VARCHAR2(255) NOT NULL,
    DT_REGISTRO TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_GS_HISTORICO_LOG PRIMARY KEY (ID_LOG),
    CONSTRAINT FK_GS_LOG_ALERTA FOREIGN KEY (ID_ALERTA)
        REFERENCES GS_ALERTAS (ID_ALERTA),
    CONSTRAINT FK_GS_LOG_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GS_USUARIOS (ID_USUARIO)
);

CREATE TABLE GS_TELEMETRIA_RAW (
    ID_PAYLOAD       NUMBER(10)  NOT NULL,
    ID_SATELITE      NUMBER(10)  NOT NULL,
    JSON_DATA        CLOB        NOT NULL,
    DT_RECEBIMENTO   TIMESTAMP   DEFAULT SYSTIMESTAMP NOT NULL,
    DS_STATUS_PROC   VARCHAR2(20) DEFAULT 'PENDENTE' NOT NULL,
    CONSTRAINT PK_GS_TELEMETRIA_RAW PRIMARY KEY (ID_PAYLOAD),
    CONSTRAINT FK_GS_TELEMETRIA_SATELITE FOREIGN KEY (ID_SATELITE)
        REFERENCES GS_SATELITES (ID_SATELITE),
    CONSTRAINT CK_GS_TELEMETRIA_JSON CHECK (JSON_DATA IS JSON),
    CONSTRAINT CK_GS_TELEMETRIA_STATUS CHECK (
        DS_STATUS_PROC IN ('PENDENTE', 'PROCESSADO', 'ERRO')
    )
);

CREATE SEQUENCE SEQ_USUARIO    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_REGIAO     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SATELITE   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ALERTA     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_LOG        START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TELEMETRIA START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE INDEX IDX_ALERTA_REGIAO   ON GS_ALERTAS (ID_REGIAO);
CREATE INDEX IDX_ALERTA_STATUS   ON GS_ALERTAS (DS_STATUS);
CREATE INDEX IDX_ALERTA_RISCO    ON GS_ALERTAS (DS_RISCO);
CREATE INDEX IDX_LOG_ALERTA      ON GS_HISTORICO_LOG (ID_ALERTA);
CREATE INDEX IDX_TELEMETRIA_SAT  ON GS_TELEMETRIA_RAW (ID_SATELITE);

COMMENT ON TABLE GS_USUARIOS IS 'Usuarios do sistema Ignis Orbital';
COMMENT ON TABLE GS_REGIOES IS 'Regioes monitoradas para prevencao de queimadas';
COMMENT ON TABLE GS_SATELITES IS 'Satelites de sensoriamento remoto';
COMMENT ON TABLE GS_ALERTAS IS 'Alertas de focos de calor detectados orbitalmente';
COMMENT ON TABLE GS_HISTORICO_LOG IS 'Auditoria de acoes sobre alertas';
COMMENT ON TABLE GS_TELEMETRIA_RAW IS 'Payloads JSON recebidos dos satelites';
