spring.application.name=ignis-orbital
server.port=8080

spring.datasource.url=${ORACLE_URL:jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl}
spring.datasource.username=${ORACLE_USER:rm559258}
spring.datasource.password=${ORACLE_PASSWORD:170904}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

ignis.messaging.enabled=false

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
